### ISSUE TITLE
VNA build

### ISSUE THREAD

**Issue by nbgsmk** [jankae/VNA#1]
Hello my friend!
I just stumbled onto your VNA project. It is great! 
After investigating various cheap VNAs on aliexpress and sucn places, I am thinking of building a VNA for myself, from your repository. I hope that would be ok for you? :-)

Among many designs I found online, this is the one I believe to deliver the most. It exceeds anything I may need, by a great degree. And I see from the documents that you really know what you are speaking about. Great work!
So, if you have the time, I would like to ask for some details:
- Somehow I missed the exact Spartan fpga used. Which is it?
- How much did the final build cost you, approximately, without the shielding and milling?
- Because of high frequencies, are there special requests for the pcb material? 
- The STM32 part is developed in StmCubeIDE?

Finally, do you have any suggestions or improvements in mind?

PS. I may get access to some RF measurement equipment so, if I am able to finish the build, I would be glad to try and do some tests or comparisons, and share my findings.

Thanks!
Zoran Kostic

**Comment by jankae** [comment]
Thanks for taking an interest in the project. First of all: I am working on a new version which you can find [here](https://github.com/jankae/VNA2)
* The FPGA is a Spartan6 (6SLX9TQG144)
* Total BOM cost was about 250€ (new version is slightly cheaper)
* Special pcb material would be better but I couldn't find an affordable manufacturer. The prototype PCB is normal FR4 (JLC7628 stackup)
* I used CubeMX + SW4STM32 for development but I believe the StmCubeIDE is essentially these two tools bundled in one IDE

**Comment by nbgsmk** [comment]
Great, let's close this question and continue in the other project.
